FROM php:7.4-cli

RUN apt-get update \
  && apt-get install -y \
    git \
    libbz2-dev \
    libicu-dev \
    libpng-dev \
    libsqlite3-dev \
    libtidy-dev \
    libxml2-dev \
    libxslt1-dev \
    libzip-dev \
    sqlite3 \
    unzip \
  && docker-php-ext-install -j$(nproc) \
    bcmath \
    bz2 \
    calendar \
    exif \
    gd \
    gettext \
    intl \
    mysqli \
    opcache \
    pcntl \
    pdo_mysql \
    pdo_sqlite \
    soap \
    sockets \
    tidy \
    xsl \
    zip

#RUN mkdir -p /usr/src/php/ext/xdebug \
#  && curl -fsSL https://pecl.php.net/get/xdebug | tar xvz -C "/usr/src/php/ext/xdebug" --strip 1 \
#  && docker-php-ext-install xdebug 

RUN git -C /tmp clone https://github.com/xdebug/xdebug.git \
  && ( \
    cd /tmp/xdebug \
    && phpize \
    && ./configure --enable-xdebug \
    && make -j "$(nproc)" \
    && make install \
  ) \
  && rm -r /tmp/xdebug \
  && docker-php-ext-enable xdebug

RUN curl -sSL https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN apt-get auto-remove -y \
  && apt-get clean
